
/*眔 產 祅篈 */
native szkp80_login(id)

/*ゴ秨 szkp80匡虫 */
native szkp80_menu(id)

/*眔 单 程蔼单 */
native szkp80_max_lv()

/*眔 產 单 单 */
native szkp80_get_level(id)

/*眔 產 单 竒喷 */
native szkp80_get_exp(id)

/*眔 產 单 ど竒喷 */
native szkp80_get_uplv_exp(id)

/*眔 疭贺单 程蔼单 */
native szkp80_max_salv()

/*眔 產 疭贺单 单 */
native szkp80_get_salevel(id)

/*眔 產 疭贺单 竒喷 */
native szkp80_get_saexp(id)

/*眔 產 疭贺单 ど竒喷 */
native szkp80_get_uplv_saexp(id)

/*眔 產 紆 计ヘ */
native szkp80_get_ammo(id)

/*眔 產 妮┦翴 翴计 */
native szkp80_get_points(id)  

/* 眔 產 ю阑 单 */
native szkp80_get_dmglv(id)

/* 眔 產 传紆硉 单 */
native szkp80_get_reloadlv(id)

/* 眔 產 畒 单 */
native szkp80_get_punchanglelv(id)

/* 眔 產 臔ヒ 单 */
native szkp80_get_armorlv(id)


/*
 	 確こ  单
*/

/* 眔  单 */
native zps_ass_level(id)

/* 眔 確こ 单 */
native zps_nem_level(id)

/* 2ノ猭:
	if (zps_ass_level(id) == 3)    // if  单 = 3
	if (zps_nem_level(id) == 1)    // if 確こ 单 = 3

	  单 = 0 or 1 or 2 or 3
	確こ单 = 0 or 1 or 2
*/

/* 眔 琌 1 */
native zps_round_asslv1()

/* 眔 琌 2 */
native zps_round_asslv2()

/* 眔 琌 3 */
native zps_round_asslv3()

/* 眔 琌 確こ1 */
native zps_round_nemlv1()

/* 眔 琌 確こ2 */
native zps_round_nemlv2()

/* 5ノ硚:璶耞 初春贾 */

native zps_assinfected()
native zps_assinfarmor()

native zps_nem_die()
native zps_ass_die()

native zps_spawn_nemass(id)