/********************************************************
	   This AMXX Made in HsK [Hong Kong]		*
		[HsK is my online name :) xD]		*
		My English is not good ~ 		*
 	  This AMXX name is   [SexR]   			*
		I hope you do not change!!		*
********************************************************/

// Usage:   if (sex_get_girl(id))
// Effect:  If this id is a girl
native sex_get_girl(id)

// Usage:   sex_set_boy(id)
// Effect:  next round become a boy
native sex_set_boy(id)

// Usage:   sex_set_girl(id)
// Effect:  next round become a girl
native sex_set_girl(id)

// Open SexR Menu
native sex_menu(id)

// Player model
native sex_player_model(id)
